apiVersion: batch/v1
kind: Job
metadata:
  name: migrator
spec:
  template:
    spec:
      containers:
      - name: migrator
        env:
        - name: GOOSE_DRIVER
          value: "postgres"
        - name: GOOSE_DBSTRING
          value: "postgres://{{ .Values.global.postgresql.auth.username }}:{{ .Values.global.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.global.postgresql.auth.database }}?sslmode=disable"
        image: {{ .Values.migrator.repository }}:{{ .Values.migrator.tag }}
        command: ["goose", "-dir", ".", "up"]
      restartPolicy: OnFailure
