logger:
  level: "DEBUG"
  format: ""

http:
  host: "localhost"
  port: 18080

storage:
  type: in-memory # possible values [in-memory, sql]
  sql:
    host: "localhost"
    port: 5432
    dbName: "test"
    driver: "pgx"
    username: "postgres"
    password: "postgres"

