logger:
  level: "DEBUG"
  format: ""

http:
  host: "localhost"
  port: 18080

grpc:
  port: 18090

amqp:
  host: "localhost"
  port: 5672
  user: ""
  password: ""  

storage:
  type: sql # possible values [memory, sql]
  sql:
    host: "localhost"
    port: 5432
    dbName: "test"
    driver: "postgres"
    username: "postgres"
    password: "postgres"

scheduler:
  pushQueue: "notifications"
  maxNotifyBefore: 86400 # in seconds
  scanEvery: 10 # in seconds
  deleteOlderThan: 360 # in seconds
  deleteEvery: 60 # in seconds

sender:
  receiveQueue: "notifications"
  pushQueue: "events"
