logger:
  level: "INFO"

http:
  host: ""
  port: 8080

storage:
  type: sql # possible values [in-memory, sql]
  sql:
    host: "localhost"
    port: 5432
    db_name: "test"
    driver: "postgres"
    username: "postgres"
    password: "postgres"

