[logger]
level = "INFO"

[http]
host = ""
port = ""

[storage]
type = "in-memory" # possible values [in-memory, sql]

[storage.sql]
host = ""
port = ""
db_name = ""
driver = ""
username = ""
password = ""

