apiVersion: v1
kind: Service
metadata:
  name: calendar
spec:
  type: LoadBalancer
  selector:
    app: calendar
    component: calendar
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: {{ .Values.calendar.http.port }}
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: {{ .Values.calendar.grpc.port }}
